### ISSUE TITLE
Not import data in table questionnaireresult

### ISSUE THREAD

**Issue by Scrik** [dolphinotaku/PPSP-360_Degree_Evaluation_System#5]
After passing the assessment and sending the data, I do not see their answers. **New records not found.**

![Снимок экрана от 2020-01-16 15-14-32](https://user-images.githubusercontent.com/5807097/72524432-fec56d00-3872-11ea-9ff9-29f43588afce.png)

PHP 7.1.33
How to turn on debug mode?

more errors in logs
> PHP Notice:  Undefined index: Field in /var/www/html/model/DatabaseManager.php on line 672, referer: http://localhost/create-evaluation-entry.html
> PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/model/DatabaseManager.php on line 672, referer: http://localhost/create-evaluation-entry.html
> PHP Notice:  Undefined offset: 0 in /var/www/html/controller/er01ir.php on line 648, referer: http://localhost/Individual-report.html
> PHP Notice:  Undefined property: stdClass::$EvaluationCode in /var/www/html/controller/ei01ep.php on line 12, referer: http://localhost/create-evaluation-entry.html
> PHP Notice:  Undefined property: stdClass::$EvaProposalID in /var/www/html/controller/ei01ep.php on line 13, referer: http://localhost/create-evaluation-entry.html
> PHP Notice:  Undefined property: stdClass::$EvaProposalID in /var/www/html/controller/ep01de.php on line 13, referer: http://localhost/create-evaluation-entry.html
>

**Comment by dolphinotaku** [comment]
Hi Scrik,

ummm.. DatabaseManager.php::672 validating is it the primary key provided in insert SQL.
The TableManager will call DatabaseManager to execute the below query to find which columns is PK and identified as necessary
```SELECT `COLUMN_NAME` AS `Field` FROM `information_schema`.`COLUMNS` WHERE (`TABLE_SCHEMA` = 'evaluation360') AND (`TABLE_NAME` = 'questionnaireresult') AND (`COLUMN_KEY` = 'PRI')```

I checked my old PC, the development and testing environment as below
![image](https://user-images.githubusercontent.com/5440966/72534490-df016980-38b1-11ea-8249-6597521327fb.png)

Could you check your table key constraints or could you please try PHP5?
I guess may some old codes not compatible in PHP7.

**Comment by Scrik** [comment]
Thanks for the answer. Today I will try PHP5

**Comment by Scrik** [comment]
Fulfilled your SQL query:
IMG: 
![Снимок экрана от 2020-01-20 11-29-38](https://user-images.githubusercontent.com/5807097/72710607-84e5fa00-3b78-11ea-89f2-6c8658298864.png)

My workstation
![Снимок экрана от 2020-01-20 11-32-55](https://user-images.githubusercontent.com/5807097/72710684-aa730380-3b78-11ea-8489-784617621d86.png)

PHPINFO

[phpinfo.zip](https://github.com/dolphinotaku/PPSP-360_Degree_Evaluation_System/files/4085169/phpinfo.zip)

**Comment by Scrik** [comment]
Will you help me?

**Comment by dolphinotaku** [comment]
It there any error prompts?
Try to provide what did server return.
Could you try the [Save draft] button, and see could the questionnaire answer saved to DB.
Then try the [Submit] button, and see could the questionnaire answer saved to DB.
![image](https://user-images.githubusercontent.com/5440966/72813104-c2907300-3c9d-11ea-8440-75cdcb266bd9.png)

**Comment by Scrik** [comment]
If you click on the draft, then: (In DB no new entries)
Processed Result:
Total 7 question answer saved.

If you click on the sumbit, then: (In DB no new entries)
Processed Result:
Questionnaire submitted.

**Draft JSON**
{"Table":"ep01de","Data":{"EvaProposalID":"266","questionnaireTable":[{"QuestionnaireID":"1","EvaluationCode":"201612","Description":"General Questionnaire for second review in the 2016."}],"ratingMarksQtnList":[{"QuestionID":"1","QuestionnaireID":"1","Question":"Consider the degree to which an activity is completed or a result produced, at the earliest time desirable from the standpoints of corrdinating with the outputs of others, maximizing the time available for other activities.","Type":"M","DisplaySequence":null,"$$hashKey":"object:27"},{"QuestionID":"2","QuestionnaireID":"1","Question":"Consider neatness, accuracy, and dependability of results regardless of volume.","Type":"M","DisplaySequence":null,"$$hashKey":"object:28"},{"QuestionID":"3","QuestionnaireID":"1","Question":"Consider the volume of work produced under normal conditions. Disregard errors.","Type":"M","DisplaySequence":null,"$$hashKey":"object:29"},{"QuestionID":"4","QuestionnaireID":"1","Question":"Consider the degree to which you carry out a job function without either having to request supervisory assistance or requiring supervisory intervention.","Type":"M","DisplaySequence":null,"$$hashKey":"object:30"},{"QuestionID":"5","QuestionnaireID":"1","Question":"Consider the degree to which you promote feelings of self-esteem, goodwill, and cooperativeness among co-workers and leaders.","Type":"M","DisplaySequence":null,"$$hashKey":"object:31"}],"openEndQtnList":[{"QuestionID":"6","QuestionnaireID":"1","Question":"Strengths (Please state 2-4 of the evaluatee's strength areas)","Type":"O","DisplaySequence":null,"$$hashKey":"object:37"},{"QuestionID":"7","QuestionnaireID":"1","Question":"Area(s) for Improvement (Please state the main area(s) that you would like the evaluatee to improve)","Type":"O","DisplaySequence":null,"$$hashKey":"object:38"}],"qtnAns":[null,"2","2","3","2","2","sad","asd"],"Submit":"D"},"Action":"ProcessData"}

**Status Draft**
{"Status":"success","Message":[],"ActionResult":{"data":[],"table_schema":null,"sql":null,"num_rows":null,"insert_id":null,"affected_rows":7,"access_status":"OK","process_result":null,"error":null,"processed_message":["Processed Result:","Total 7 question answer saved."]}}

**Sumbit JSON**
{"Table":"ep01de","Data":{"EvaProposalID":"266","questionnaireTable":[{"QuestionnaireID":"1","EvaluationCode":"201612","Description":"General Questionnaire for second review in the 2016."}],"ratingMarksQtnList":[{"QuestionID":"1","QuestionnaireID":"1","Question":"Consider the degree to which an activity is completed or a result produced, at the earliest time desirable from the standpoints of corrdinating with the outputs of others, maximizing the time available for other activities.","Type":"M","DisplaySequence":null,"$$hashKey":"object:27"},{"QuestionID":"2","QuestionnaireID":"1","Question":"Consider neatness, accuracy, and dependability of results regardless of volume.","Type":"M","DisplaySequence":null,"$$hashKey":"object:28"},{"QuestionID":"3","QuestionnaireID":"1","Question":"Consider the volume of work produced under normal conditions. Disregard errors.","Type":"M","DisplaySequence":null,"$$hashKey":"object:29"},{"QuestionID":"4","QuestionnaireID":"1","Question":"Consider the degree to which you carry out a job function without either having to request supervisory assistance or requiring supervisory intervention.","Type":"M","DisplaySequence":null,"$$hashKey":"object:30"},{"QuestionID":"5","QuestionnaireID":"1","Question":"Consider the degree to which you promote feelings of self-esteem, goodwill, and cooperativeness among co-workers and leaders.","Type":"M","DisplaySequence":null,"$$hashKey":"object:31"}],"openEndQtnList":[{"QuestionID":"6","QuestionnaireID":"1","Question":"Strengths (Please state 2-4 of the evaluatee's strength areas)","Type":"O","DisplaySequence":null,"$$hashKey":"object:37"},{"QuestionID":"7","QuestionnaireID":"1","Question":"Area(s) for Improvement (Please state the main area(s) that you would like the evaluatee to improve)","Type":"O","DisplaySequence":null,"$$hashKey":"object:38"}],"qtnAns":[null,"2","2","3","2","2","sad","asd"],"Submit":"S"},"Action":"ProcessData"}

**Status JSON**
{"Status":"success","Message":[],"ActionResult":{"data":[],"table_schema":null,"sql":null,"num_rows":null,"insert_id":null,"affected_rows":7,"access_status":"OK","process_result":null,"error":null,"processed_message":["Processed Result:","Questionnaire submitted."]}}

**Comment by Scrik** [comment]
if I give you a link to the site, you can determine what the problem is?

**Comment by dolphinotaku** [comment]
this is my json request
`{"Table":"ep01de","Data":{"EvaProposalID":"559","questionnaireTable":[{"QuestionnaireID":"5","EvaluationCode":"202006","Description":"first review in 2020"}],"ratingMarksQtnList":[{"QuestionID":"82","QuestionnaireID":"5","Question":"Could you please rate the PPSP system?","Type":"M","DisplaySequence":"1","$$hashKey":"object:54"},{"QuestionID":"83","QuestionnaireID":"5","Question":"Could you please rate the Community?","Type":"M","DisplaySequence":"2","$$hashKey":"object:55"}],"openEndQtnList":[{"QuestionID":"84","QuestionnaireID":"5","Question":"How did you know us?","Type":"O","DisplaySequence":"1","$$hashKey":"object:58"},{"QuestionID":"85","QuestionnaireID":"5","Question":"Would you go to use PPSP in your company?","Type":"O","DisplaySequence":"2","$$hashKey":"object:59"}],"qtnAns":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"2","3","hi1","hi2"],"Submit":"D"},"Action":"ProcessData"}`
![image](https://user-images.githubusercontent.com/5440966/72815454-a1318600-3ca1-11ea-8fe7-37f478d2da14.png)

it seems some null are missing in the JSON, which browser and version do you use?

**Comment by Scrik** [comment]
Firefox , Chrome with latest updates
http://360.tlabs.ru/   - testing site, standart login and pass

**Comment by Scrik** [comment]
What OS are you using?


He must assign a value? Because of this, he does not enter the database?
![Снимок экрана от 2020-01-22 13-18-22](https://user-images.githubusercontent.com/5807097/72885865-d083d980-3d19-11ea-80e3-63242a9787dc.png)

**Comment by dolphinotaku** [comment]
I answered some questionnaire on 360 Degree Evaluation Entry on your provided link.

**Comment by Scrik** [comment]
in table "questionnaireresult" without changes

**Comment by Scrik** [comment]
What else can I see? where to dig?

**Comment by dolphinotaku** [comment]
I am using Wins, I can see the "question" table records updated after I clicked [Save as Draft].
I have no idea at the current moment why cannot insert records to "questionnaireresult" on client side, I think you better to debug in PHP, try to print_r and check the SQL insert query and the execute result.

**Comment by Scrik** [comment]
On Windows 10, everything worked out !
Then why with the same versions and libraries on Linux not work? Any ideas? on Linux there is only OfficetoPDF

**Comment by dolphinotaku** [comment]
The programming practice not in full safety for cross-OS, some code snippet should use DIRECTORY_SEPARATOR instead of using "/" or "\", and I am not sure is all third-parties work normally under Linux/Unix/*nix.

**Comment by Scrik** [comment]
I will try to find a problem, as soon as I know something, I will inform you.(I'll try today or tomorrow)

I also tried on Windows with PHP 7.3 and everything works fine there.
