### ISSUE TITLE
Create webuser

### ISSUE THREAD

**Issue by Scrik** [dolphinotaku/PPSP-360_Degree_Evaluation_System#6]
When importing users, webuser is not created?
Is it possible to do something in automatic mode create webuser and connect with staff?

**Comment by dolphinotaku** [comment]
Unfortunately, the user management not included in the scope at the beginning.
For this, need to amend eu01sf.php, I have made some changes below, you need to retrieve the newly imported staff records.
```
function ImportData($httpRequest){
	$responseArray = array();
	$fileExistsInUploadFolder = false;
	$fileExistsInUserFolder = false;

	$importManager = new ExcelManager();
	$importManager->Initialize();
	
	$importManager->AddTable("staff");

	$responseArray = Core::CreateResponseArray();

	$requestData = new stdClass();
	$requestData = $httpRequest; //->Data->Header;

	$fileInfo = new stdClass();

	if(is_array($requestData->FileUploadedResult)){
		$fileInfo = $requestData->FileUploadedResult[0];
	}
	$excelFileLocation = $fileInfo->movedTo;

	// move file to user folder if user is valid
	$userID = "";
	$securityManager = new SecurityManager();

	if(file_exists($excelFileLocation))
		$fileExistsInUserFolder = true;

	if($fileExistsInUserFolder)
		$responseArray = $importManager->Import($excelFileLocation);
    
    // 20200128, Get imported Staff list
	$webuserManager = new WebuserManager();
    $createdStaffList = array();
    
    // 20200128, Create webuser records
	foreach ($createdStaffList as $keyIndex => $createdStaff) {
        // read the staff record
        $staffBirthDay = date('Ymd');
        $staffID = "";
        
		$webuserManager->LoginID = $staffID;
		$webuserManager->Password = $securityManager->Hash($staffBirthDay);
		$webuserManager->AccountType = "staff";
		$webuserManager->ActivateDate = date('Y-m-d H:i:s');
		$webuserManager->Status = "a";
        
		$webuserInsertResultArray = $webuserManager->insert();
	}

	return $responseArray;
}
```

If you target to create webuser record at the same time when staff record created.
Better to add below features to the system that would be better.

- Change password function for the webuser
- Reset password function for the admin to reset the password for who forgot the password

**Comment by Scrik** [comment]
I deleted all users again, and when importing a user with your code **webuser was not created**. There are no errors. 



[eu01sf.txt](https://github.com/dolphinotaku/PPSP-360_Degree_Evaluation_System/files/4134024/eu01sf.txt)

**Comment by Scrik** [comment]
To create webuser I add trigger in MySQL:

CREATE TRIGGER `create_webuser` AFTER INSERT ON `staff`
 FOR EACH ROW INSERT INTO webuser SET LoginID=NEW.StaffID, Password="0000000000adsad0asdasd0asd0asd0as0das0das0dasd", AccountType="staff", ActivateDate="2020-02-02 00:00:00", Status="a"



But how to add to table staff update field USERID?
**Answered himself:**
UPDATE staff INNER JOIN webuser
ON webuser.LoginID=staff.StaffID
SET staff.UserID=webuser.UserID

**Comment by dolphinotaku** [comment]
My code required to get the list of created staffs
```
    $createdStaffList = array();
    // write your code here
    // option 1, read the uploaded excel and extract the staff record
    // option 2, select all records from the staff table stored as beforeList, import the staff records
    // select all records from staff table stored as afterList, compare the list difference and insert webuser records
    // 20200128, Create webuser records
    // write your code here
```

As an alternative, create DB trigger is good at the current moment.
I hope can spend time to improve this in the future

**Comment by dolphinotaku** [comment]
The optimistic view should be creating below new functions 
For admin user
- Generate WebUsers a/c
- Send Email to the newly created webuser with the login instructions
- Reset pwd
For admin, general user
- Change pwd

### Generate WebUsers a/c
List the staff records who without webuser ac
User select staff record(s) to generate corresponding webuser ac

### Send Account Created Email
List the webuser ac which is newly created
User select webuser record(s) to send notification email with login instructions

### Reset pwd
Allows admin user to reset the webuser pwd, send email notification to webuser with login instructions

### Change pwd
Allows user to change account pwd by themself

**Comment by dolphinotaku** [comment]
I will mark this in the future plan
